version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Password123
    ports:
      - "1433:1433"
    volumes:
      - electropm_sqldata:/var/opt/mssql/data
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong@Password123", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    container_name: electro_pm_api
    ports:
      - "8080:5273"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5273
      - DOTNET_LAUNCH_PROFILE=""
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ElectroPmDb;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=True;
      - JwtSettings__Key=YourSuperSecretBackingKeyThatIsVeryLongAndSecure123!
      - JwtSettings__Issuer=ElectroPmApi
      - JwtSettings__Audience=ElectroPmClient
    depends_on:
      sqlserver:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./API
          target: /app/API
        - action: sync
          path: ./Infrastructure
          target: /app/Infrastructure
        - action: sync
          path: ./Application
          target: /app/Application
        - action: sync
          path: ./Domain
          target: /app/Domain

volumes:
  electropm_sqldata: